In [203]:
import tensorflow as tf
from tensorflow import Variable, GradientTape
from tensorflow.math import exp, log, pow

In [253]:
def f(x, w, b): return w * x + b
def sigmoid(x, w, b): return 1 / (1 + exp(-f(x, w, b)))

def dsdx(x, w, b):
    a = sigmoid(x, w, b)
    return a * (1 - a) * w

def dsdw(x, w, b): 
    a = sigmoid(x, w, b)
    return a * (1 - a) * x

def autograd(fun, val, delta=0.0006):
    return (fun(val + delta) - fun(val)) / delta

In [296]:
x = Variable([-1.0], dtype="float64")
w1 = Variable([4.0], dtype="float64")
b1 = Variable([-1.1], dtype="float64")
w2 = Variable([-1.9], dtype="float64")
b2 = Variable([3.9], dtype="float64")

In [297]:
with GradientTape() as tape:
    a1 = sigmoid(x, w1, b1)
    a2 = sigmoid(a1, w2, b2)

In [298]:
tape.gradient(a2, [w2, b2, w1, b1])

[<tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.00011915])>,
 <tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.01966283])>,
 <tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.00022502])>,
 <tf.Tensor: shape=(1,), dtype=float64, numpy=array([-0.00022502])>]

In [299]:
def w1sigmoid(w1):
    return sigmoid(sigmoid(x, w1, b1), w2, b2)
def b1sigmoid(b1):
    return sigmoid(sigmoid(x, w1, b1), w2, b2)
def w2sigmoid(w2):
    return sigmoid(sigmoid(x, w1, b1), w2, b2)
def b2sigmoid(b2):
    return sigmoid(sigmoid(x, w1, b1), w2, b2)

In [300]:
autograd(w2sigmoid, w2)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.00011915])>

In [301]:
autograd(b2sigmoid, b2)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.01965717])>

In [302]:
autograd(w1sigmoid, w1)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.00022495])>

In [303]:
autograd(b1sigmoid, b1)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([-0.00022509])>

In [306]:
def dw2(inp):
    a = sigmoid(inp, w2, b2)
    return a * (1 - a) * inp

In [307]:
dw2(a1)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.00011915])>